baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'dudozer_maks'
theme = 'customTheme'

[markup]
	[markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.highlight]
		lineNos = true
    style = 'gruvbox'

[output]
animations = ['html']
